
server:
    port: 8085

spring:
    application.name: manulife_crud
    datasource:
        # DATABASE
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/db_manulife?zeroDateTimeBehavior=convertToNull
        username: user_local
        password: auUmc2FutKX5frJad3uVpNM5mnbXhzS53AygPwijprD9qfabKYebggJpJKcWCN9NmQpUf7QM7wFcyg7AWMLhFTdHXy34fX7zvrMjbe9usMnPpAWS9KF779XTEAEQE22s

    jpa:
        show-sql: true
        hibernate.ddl-auto: create
        database: default
        properties:
            hibernate:
                format_sql: true
                check_nullability: true
                jdbc.time_zone: Asia/Jakarta
                dialect: org.hibernate.dialect.MariaDBDialect
        database-platform: org.hibernate.MariaDBDialect
        defer-datasource-initialization: true